<a href="https://colab.research.google.com/github/jo-cho/memos/blob/master/RL/sentdex_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import gym
import numpy as np
import matplotlib.pyplot as plt
from IPython import display as ipythondisplay

RL

In [0]:
!pip install -q pyvirtualdisplay
!sudo apt-get install xvfb

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-430
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 783 kB of archives.
After this operation, 2,266 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 xvfb amd64 2:1.19.6-1ubuntu4.3 [783 kB]
Fetched 783 kB in 0s (6,741 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype

In [0]:
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!


<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>

In [0]:
env = gym.make("MountainCar-v0")
env.reset()
#3개의 액션

print(env.observation_space.high)
print(env.observation_space.low)
print(env.action_space.n)

discrete_os_size = [20]*len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high - env.observation_space.low) / discrete_os_size

print(discrete_os_win_size)

q_table = np.random.uniform(low=-2, high=0, size=discrete_os_size + [env.action_space.n]) #20x20x3 즉 모든 combination of observation(position and velocity) 
#위는 radom q values라고 보면 됨.
print(q_table.shape)
print(q_table)


done = False

while not done:
  action = 2 
  # push the card right
  new_state, reward, done, _ = env.step(action)
  print(reward, new_state)
  env.render()
  
env.close()

[0.6  0.07]
[-1.2  -0.07]
3
[0.09  0.007]
(20, 20, 3)
[[[-1.37072828 -0.52317054 -0.25976595]
  [-0.0310172  -0.21478545 -1.86051356]
  [-0.93074496 -0.96331205 -0.37557957]
  ...
  [-1.73721422 -0.55982299 -1.20912195]
  [-0.35649262 -1.51350703 -0.75445467]
  [-0.67306527 -1.6724355  -1.93525298]]

 [[-0.63159717 -1.38272901 -0.64441759]
  [-0.57831942 -0.81938307 -0.60105301]
  [-1.25320895 -1.59529356 -1.68207325]
  ...
  [-0.10127213 -0.74647875 -1.54433951]
  [-1.63703447 -1.00843689 -0.42318378]
  [-0.86938612 -0.66186667 -1.50669083]]

 [[-0.06796255 -1.42062158 -1.77489514]
  [-0.5515004  -0.82507906 -1.16779427]
  [-0.38630845 -0.07178784 -0.30893944]
  ...
  [-1.84514838 -1.85803267 -1.84910465]
  [-1.15603192 -1.19263367 -1.50313825]
  [-1.42120081 -1.48772869 -1.88163783]]

 ...

 [[-0.03766392 -0.52662211 -1.06206386]
  [-0.93094682 -1.21437538 -0.84982798]
  [-0.12479046 -1.03479965 -0.06524278]
  ...
  [-0.19913868 -0.13676593 -0.48532606]
  [-1.9912438  -0.79113318 -0.